source 'https://rubygems.org'

gem 'sinatra', '<= 1.3.5'
gem 'dm-core'
gem 'dm-postgres-adapter'
gem 'dm-migrations'
gem 'data_mapper'
gem 'builder'
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
